name: Benchmarks
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - '**/*.ts'
      - '**/*.js'
      - 'package.json'
jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
      - run: corepack enable && pnpm install --frozen-lockfile
        working-directory: zern-kernel
      - run: pnpm run bench:lifecycle
        working-directory: zern-kernel
