name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    name: Test & Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint code
        run: pnpm run lint

      - name: Type check
        run: pnpm run type-check

      - name: Run tests with coverage
        run: pnpm run test:coverage

      - name: Generate coverage badges
        run: npx --yes coverage-badges --source coverage/coverage-summary.json --output coverage/badges.svg || true

      - name: Generate shields endpoint (coverage)
        run: pnpm coverage:endpoint || true

      - name: Upload coverage artifacts (including badges)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-badges
          path: |
            ./coverage/badges.svg
            ./coverage/coverage-summary.json
            ./coverage/coverage-endpoint.json
          if-no-files-found: ignore
          retention-days: 30

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage/coverage-final.json
          flags: kernel
          name: kernel-coverage
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Comment coverage on PR
        if: github.event_name == 'pull_request'
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./coverage/lcov.info
          delete-old-comments: true

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            ./coverage/
            !./coverage/tmp/
          retention-days: 30

  update-coverage-badge:
    name: Update Coverage Badge
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Download coverage badges
        uses: actions/download-artifact@v4
        with:
          name: coverage-badges
          path: ./coverage/

      - name: Commit coverage badges
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f coverage/badges.svg coverage/coverage-summary.json coverage/coverage-endpoint.json README.md
          git diff --staged --quiet || git commit -m "chore: update coverage badges [skip ci]"
          git push
