name: OpenSSF Scorecard
on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
  schedule: [{ cron: '0 6 * * 1' }]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  analysis:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      security-events: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: ossf/scorecard-action@v2.4.0
        with:
          results_file: results.sarif
          results_format: sarif
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          publish_results: true

      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
