name: OpenSSF Scorecard
on:
  push:
    branches: [main]
    paths:
      - '**/*.ts'
      - '**/*.js'
      - 'package.json'
  schedule: [{ cron: '0 6 * * 1' }]
permissions:
  contents: read
jobs:
  analysis:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - uses: ossf/scorecard-action@v2.3.3
        with:
          results_file: results.sarif
          results_format: sarif
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          publish_results: true
      - uses: github/codeql-action/upload-sarif@v3
        with: { sarif_file: results.sarif }
